### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by yacaeh** [alyssaxuu/figma-platformer-engine#1]
Hi, thank you for the awesome project.

However I'm pretty new to figma so I don't have a clue how to start this to work. Should I export it to html with the code to work with?

**Comment by alyssaxuu** [comment]
I'm not sure what you mean - do you mean in order to export the game you created? I haven't added a function for that myself, but that could be implemented. If you mean how to use the code itself though, you can use https://alyssax.com/x/platformer & follow the instructions there.

**Comment by yacaeh** [comment]
Oh.. I didn't know I should paste my Figma link to the file URL after that page. It works now, thank you!
